### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by nicorl** [abhijaykumar/serverless-posts-api#1]
Hello,

When I tried to deploy, system has returned me this message.

```
Serverless: Docker Image: lambci/lambda:build-python3.8

  Error --------------------------------------------------

  Error: docker not found! Please install it.
```

Why this kind of solution needs Docker? I didn't read anything about it. 

Thanks!

**Comment by nicorl** [comment]
I've installed Docker and after that I found another problem 

```
Serverless: Docker Image: lambci/lambda:build-python3.8

  Error --------------------------------------------------

  Error: unable to resolve docker endpoint: open C:\Users\nico\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
```

I solved the situation by using terminal as administrator.

**Comment by abhijaykumar** [comment]
@nicorl Apologies for the lates response. Docker will be needed if you are on a non-linux environement as defined in the `serverless.yml` file
```
custom:
  pythonRequirements:
    dockerizePip: non-linux
```
So you will need docker to be installed on Windows. This is needed for [Compiling of non-pure-Python modules](https://stackoverflow.com/questions/58663920/can-i-run-docker-desktop-on-windows-without-admin-privileges). 
Also, in your second query Docker always needs administrator privileges to run properly. See [this](https://stackoverflow.com/questions/58663920/can-i-run-docker-desktop-on-windows-without-admin-privileges).

I'm glad you figured it out. I will update this information in my post.

Thanks

**Comment by nicorl** [comment]
Thanks :-) 

Have a nice day.
